# Numpy
---
- 创建 NumPy 数组：
    - 通过 dataframe：pandas.DataFrame.values
    - 通过 Python 序列：numpy.array
    - 使用常量初始值：numpy.ones、numpy.zeros
    - 使用随机值：numpy.random
- 访问数组属性：shape、ndim、size、dtype
- 计算统计值：sum、min、max、mean
- 进行算术运算：add、subtract、multiply、divide
- 衡量执行时间：time.time、profile
- 操纵数组元素：使用简单的索引和切片、整数数组、布尔型数组


In [17]:
import numpy as np

# Array
print(np.array([(2,3,4), (5,6,7)]))
print(np.empty(5))
print(np.zeros((5,3), dtype=np.float_))
print(np.ones((5,3)))

[[2 3 4]
 [5 6 7]]
[4.0e-323 4.0e-323 4.0e-323 3.0e-323 3.5e-323]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Random functions

- numpy.random.random：从范围为 [0.0, 1.0) 的均匀分布中抽样
- numpy.random.rand：与 random 相似，但是语法有所不同
- numpy.random.normal：正态或高斯分布
- numpy.random.randint：整数来自均匀分布


In [21]:
# Generate an array full of random numbers, uniformly sampled from [0.0, 1.0] 
print(np.random.random((5,4)))  # function arguments is a tuple
print(np.random.rand(5,4))  # function arguments is not a tuple

# Sample numbers from a Gaussian (normal) distribution
print(np.random.normal(50,10, size=(2,3))) # mean: 50, std: 10

# Random Integers
print(np.random.randint(10)) # a single integer in [0.10).
print(np.random.randint(0,10)) # same as above, specifiying [low, high) explicit.
print(np.random.randint(0,10,size=5)) # 5 random integers as a 1D array.
print(np.random.randint(0,10,size=(2,3))) # 2*3 array of random integers.

[[0.1229821  0.4570553  0.48826977 0.23819149]
 [0.52598825 0.8464826  0.74861028 0.0374242 ]
 [0.92671146 0.76910865 0.62771074 0.73228147]
 [0.16956415 0.37682219 0.64555493 0.8481747 ]
 [0.91264059 0.66087306 0.34062062 0.93897751]]
[[0.98842249 0.69220931 0.69900917 0.19204272]
 [0.37874478 0.71584169 0.3620873  0.38159081]
 [0.21945143 0.57643217 0.48952388 0.43039382]
 [0.86203378 0.67087957 0.67709459 0.11760238]
 [0.93596295 0.69289291 0.12688465 0.43814822]]
[[37.01296316 47.60601374 57.87336446]
 [57.98137346 37.87974201 45.18050092]]
6
3
[5 5 4 1 8]
[[7 5 8]
 [9 0 7]]


## Numpy.ndarray Property
- numpy.ndarray.shape：维度（高、宽…）
- numpy.ndarray.ndim：维数 = len(shape)
- numpy.ndarray.size：元素总数
- numpy.ndarray.dtype：数据类型


## Numpy.ndarray Math Function
- numpy.sum：行、列或整个数组的元素之和
- numpy.min、numpy.max、numpy.mean：简单统计数据
- numpy.random.seed 可以设置（重置）随机数生成器。

In [4]:
import numpy as np

np.random.seed(693)
a = np.random.randint(0,10, size=(5,3))
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.sum)

[[2 0 5]
 [1 1 3]
 [4 4 9]
 [2 9 1]
 [9 3 7]]
(5, 3)
15
2
<built-in method sum of numpy.ndarray object at 0x7fdbba56f760>
