# Numpy Basics
---
- 创建 NumPy 数组：
    - 通过 dataframe：pandas.DataFrame.values
    - 通过 Python 序列：numpy.array
    - 使用常量初始值：numpy.ones、numpy.zeros
    - 使用随机值：numpy.random
- 访问数组属性：shape、ndim、size、dtype
- 计算统计值：sum、min、max、mean
- 进行算术运算：add、subtract、multiply、divide
- 衡量执行时间：time.time、profile
- 操纵数组元素：使用简单的索引和切片、整数数组、布尔型数组


In [3]:
import numpy as np

# Array
print(np.array([(2,3,4), (5,6,7)]))
print(np.empty(5))
print(np.zeros((5,3), dtype=np.float_))
print(np.ones((5,3)))

[[2 3 4]
 [5 6 7]]
[1.39716487e-311 1.39718919e-311 1.39716940e-311 9.66174105e-315
 1.39716603e-311]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Random functions

- numpy.random.random：从范围为 [0.0, 1.0) 的均匀分布中抽样
- numpy.random.rand：与 random 相似，但是语法有所不同
- numpy.random.normal：正态或高斯分布
- numpy.random.randint：整数来自均匀分布


In [4]:
# Generate an array full of random numbers, uniformly sampled from [0.0, 1.0] 
print(np.random.random((5,4)))  # function arguments is a tuple
print(np.random.rand(5,4))  # function arguments is not a tuple

# Sample numbers from a Gaussian (normal) distribution
print(np.random.normal(50,10, size=(2,3))) # mean: 50, std: 10

# Random Integers
print(np.random.randint(10)) # a single integer in [0.10).
print(np.random.randint(0,10)) # same as above, specifiying [low, high) explicit.
print(np.random.randint(0,10,size=5)) # 5 random integers as a 1D array.
print(np.random.randint(0,10,size=(2,3))) # 2*3 array of random integers.

[[0.69644337 0.88891619 0.54776307 0.89595466]
 [0.13743521 0.06549335 0.3582576  0.93210058]
 [0.36999407 0.42452879 0.53058181 0.37107721]
 [0.91321629 0.09798039 0.48698688 0.0853557 ]
 [0.183963   0.91459903 0.5941312  0.03791784]]
[[0.89442571 0.36707454 0.25388651 0.70571736]
 [0.29391278 0.14669698 0.77860858 0.79152787]
 [0.38503043 0.78908741 0.86884039 0.03193832]
 [0.76515813 0.85116279 0.24843349 0.65618367]
 [0.12282487 0.3317606  0.29181202 0.88206798]]
[[40.28812672 62.31102436 39.04089493]
 [48.73033481 47.21695268 60.77641675]]
6
5
[1 7 6 9 8]
[[5 8 3]
 [2 2 8]]


## Numpy.ndarray Property
- numpy.ndarray.shape：维度（高、宽…）
- numpy.ndarray.ndim：维数 = len(shape)
- numpy.ndarray.size：元素总数
- numpy.ndarray.dtype：数据类型


## Numpy.ndarray Math Function
- numpy.sum：行、列或整个数组的元素之和
- numpy.min、numpy.max、numpy.mean：简单统计数据
- numpy.random.seed 可以设置（重置）随机数生成器。

In [10]:
import numpy as np

np.random.seed(693)
a = np.random.randint(0,10, size=(5,3))
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.sum(axis=1))
print(a.min(axis=1))
print(a.max(axis=1))
print(a.sum(axis=0))
print(a.min(axis=0))
print(a.max(axis=0))


[[2 0 5]
 [1 1 3]
 [4 4 9]
 [2 9 1]
 [9 3 7]]
(5, 3)
15
2
[ 7  5 17 12 19]
[0 1 4 1 3]
[5 3 9 9 9]
[18 17 25]
[1 0 1]
[9 9 9]


## Numpy.ndarray Max index


In [14]:
a = np.array([9, 6, 2, 3, 12, 14, 7, 10], dtype=np.int32)  # 32-bit integer array
print("Array: ", a)
print("Max is:", a.max())
print("Max index: ", a.argmax())

Array:  [ 9  6  2  3 12 14  7 10]
Max is: 14
Max index:  5


## Record Exectuion Time

- time.time：当前时间（浮点值，以秒计）
- timeit：衡量平均执行时间
- profile：分析代码

iPython“魔法函数”：

- %time：运行一次的时间
- %timeit：多次运行的平均时间
- %prun/%lprun：分析每个函数/每行代码


In [1]:
import time
t1 = time.time()
print("hello")
print("Time elapsed: " , time.time()-t1)


hello
Time elapsed:  0.0


## Indexing 
表达式 a < mean 会生成一个布尔型数组，例如：

```python
[[False, False, True, False, False, False, True, True, True],
 [True, True, False, False, True, True, False, True, True]]
```

使用上述数组对数组 a 设定索引时，只有值为 True 的位置才会选中，并且这些值将添加到列表中。


NumPy 参考文档：算术运算
-    numpy.add：元素级加法，与 + 运算符相同
-    numpy.subtract：元素级减法，与 - 相同
-    numpy.multiply：元素级乘法，与 * 相同
-    numpy.divide：元素级除法，与 / 相同
-    numpy.dot：点积（一维数组）、矩阵乘法（二维数组）

注意：数组相互之间必须兼容，才能进行这些运算（请参阅：广播）。

